name: Continuous integration

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Style checks via pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Custom RST checks (check-rst.sh)
        run: |
          bash ./_tools/check-rst.sh
